In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/kaggle/input/datasets/divjotbedi/customer-dataset-with-education-age-gender/customer.csv')

In [3]:
df.head(10)

   age  gender purchased     review education
0   58    Male       Yes       Good        UG
1   32    Male       Yes       Poor    School
2   45    Male       Yes       Poor        UG
3   32    Male       Yes  Excellent        UG
4   46  Female       Yes    Average    School
5   45  Female        No    Average        UG
6   66  Female       Yes       Poor        PG
7   24  Female        No       Good        UG
8   64  Female       Yes  Excellent        UG
9   53  Female        No    Average    School

In [5]:
from sklearn.model_selection import train_test_split

In [10]:
train_X,test_X,train_y,test_y=train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2,random_state=42)

In [11]:
train_X

     age  gender     review education
249   44  Female  Excellent        PG
433   43    Male    Average        PG
19    26    Male  Excellent    School
322   36  Female  Excellent        PG
332   19  Female       Good        UG
..   ...     ...        ...       ...
106   52    Male    Average        UG
270   37    Male       Good        PG
348   58    Male  Excellent        PG
435   33  Female       Good        PG
102   46    Male  Excellent        PG

[400 rows x 4 columns]

In [12]:
test_X

     age  gender     review education
361   63    Male    Average        UG
73    61    Male       Good    School
374   20  Female  Excellent    School
155   46  Female       Good    School
104   33  Female       Poor    School
..   ...     ...        ...       ...
347   46    Male  Excellent        PG
86    45    Male       Good    School
75    44    Male       Good        PG
438   28  Female       Poor    School
15    35    Male       Poor        UG

[100 rows x 4 columns]

In [55]:
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [60]:
transformer=ColumnTransformer(transformers=[
                              ('tnf1',OrdinalEncoder(categories=[['Poor', 'Average', 'Good', 'Excellent'],['School', 'UG', 'PG']]), ['review', 'education']),
                              ('tnf2',OneHotEncoder(sparse_output=False,drop='first'),['gender'])],
                             remainder='passthrough')

In [64]:
train_X_tranformed=transformer.fit_transform(train_X)
train_X_tranformed=pd.DataFrame(train_X_tranformed,columns=['review','education','female','age'])

In [67]:
test_X_tranformed=transformer.fit_transform(test_X)
test_X_tranformed=pd.DataFrame(test_X_tranformed,columns=['review','education','female','age'])

In [66]:
train_X_tranformed.head(10)

   review  education  female   age
0     3.0        2.0     0.0  44.0
1     1.0        2.0     1.0  43.0
2     3.0        0.0     1.0  26.0
3     3.0        2.0     0.0  36.0
4     2.0        1.0     0.0  19.0
5     1.0        0.0     0.0  60.0
6     1.0        0.0     0.0  53.0
7     3.0        2.0     0.0  20.0
8     2.0        0.0     0.0  58.0
9     1.0        1.0     0.0  70.0

In [68]:
test_X_tranformed.head(10)

   review  education  female   age
0     1.0        1.0     1.0  63.0
1     2.0        0.0     1.0  61.0
2     3.0        0.0     0.0  20.0
3     2.0        0.0     0.0  46.0
4     0.0        0.0     0.0  33.0
5     2.0        0.0     0.0  24.0
6     1.0        2.0     1.0  47.0
7     2.0        0.0     1.0  37.0
8     1.0        0.0     1.0  67.0
9     0.0        1.0     0.0  45.0